name: donation
description: A new Flutter project.

publish_to: "none"

version: 1.3.9+167

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  animated_widgets: ^1.1.0
  # charts_flutter: ^0.12.0
  #cloud_firestore: ^4.7.0
  cached_network_image: ^3.3.0
  desktop_window: ^0.4.0
  dio: ^5.3.3
  dotted_line: ^3.2.2
  dropdown_button2: ^2.3.9
  equatable: ^2.0.5
  # firebase_auth: ^4.12.1
  # firebase_core: ^2.21.0
  # firebase_messaging: ^14.7.3
  fl_chart: ^0.69.0
  fluent_ui: ^4.7.5
  flutter:
    sdk: flutter
  flutter_cupertino_date_picker_fork: ^1.0.7
  flutter_custom_dialog: ^1.3.0
  flutter_expandable_table: ^2.0.0
  flutter_hooks: ^0.20.5
  flutter_image_compress: ^2.0.4
  flutter_image_slideshow: ^0.1.6
  flutter_local_notifications: ^17.2.3
  flutter_localizations:
    sdk: flutter
  flutter_neumorphic: ^3.2.0
  flutter_rounded_date_picker: ^3.0.3
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.6
  flutter_typeahead: ^4.3.8
  flutter_zoom_drawer: ^3.1.1
  # google_fonts: ^2.3.2

  google_fonts: ^6.2.1
  hooks_riverpod: ^2.3.6
  http: ^1.2.2
  image_picker: ^1.0.2
  infinite_scroll_pagination: ^4.0.0
  internet_connection_checker: ^1.0.0+1
  logger: ^2.4.0
  modal_progress_hud_nsn: ^0.5.1
  month_picker_dialog: ^5.1.3
  path_provider: ^2.1.0
  pin_code_fields: ^8.0.1
  readmore: ^3.0.0
  realm: ^1.0.3
  responsive_framework: ^1.1.1
  riverpod_annotation: ^2.1.1

  rxdart: ^0.28.0
  shared_preferences: ^2.1.1
  shimmer: ^3.0.0
  syncfusion_flutter_charts: ^27.1.52
  syncfusion_flutter_datagrid: ^27.1.52
  tab_container: ^3.5.3
  tar: ^1.0.5
  transparent_image: ^2.0.1
  url_launcher: ^6.1.11
  win32: ^5.5.5

dependency_overrides: 
  intl: ^0.19.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.6.2
  build_runner: ^2.4.4
  msix: ^3.12.2
  custom_lint: ^0.6.8
  #riverpod_lint: ^1.3.2
  riverpod_generator: ^2.2.3

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
    - assets/json/
    - shorebird.yaml

  fonts:
    - family: TwitterIcon
      fonts:
        - asset: assets/fonts/icons.ttf
    - family: MyanUni
      fonts:
        - asset: assets/fonts/MyanUni/pds_regular.ttf
    - family: YT
      fonts:
        - asset: assets/fonts/yt.ttf
    - family: MS
      fonts:
        - asset: assets/fonts/myan_san.ttf

msix_config:
  display_name: Safe Blood
  msix_version: 1.25.1.1
  logo_path: C:\my_project\donation\favicon.ico
  start_menu_icon_path: C:\my_project\donation\ic_launcher.png
  tile_icon_path: C:\my_project\donation\ic_launcher.png
