name: donation
description: A new Flutter project.

publish_to: "none"

version: 1.2.3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  animated_widgets: ^1.1.0
  # charts_flutter: ^0.12.0
  #cloud_firestore: ^4.7.0
  cached_network_image: ^3.2.3
  dio: ^5.1.2
  dotted_line: ^3.1.0
  dropdown_button2: ^2.1.2
  #firebase_core: ^2.12.0
  equatable: ^2.0.5
  firebase_analytics: ^10.4.5
  firebase_auth: ^4.8.0
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.7
  firebase_storage: ^11.2.6
  fl_chart: ^0.62.0
  fluent_ui: ^4.6.1
  flutter:
    sdk: flutter
  flutter_cupertino_date_picker_fork: ^1.0.7
  flutter_custom_dialog: ^1.3.0
  flutter_expandable_table: ^2.0.0
  flutter_hooks: ^0.18.6
  flutter_image_compress: ^2.0.4
  flutter_image_slideshow: ^0.1.6
  flutter_local_notifications: ^15.1.1
  flutter_localizations:
    sdk: flutter
  flutter_neumorphic: ^3.2.0
  flutter_rounded_date_picker: ^3.0.3
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.6
  flutter_typeahead: ^4.3.8
  flutter_zoom_drawer: ^3.1.1
  # google_fonts: ^2.3.2
  
  google_fonts: ^4.0.4
  hooks_riverpod: ^2.3.6
  http: ^0.13.6
  image_picker: ^1.0.2
  infinite_scroll_pagination: ^3.2.0
  logger: ^1.3.0
  modal_progress_hud_nsn: ^0.4.0
  path_provider: ^2.1.0
  pin_code_fields: ^8.0.1
  realm: ^1.0.3
  riverpod_annotation: ^2.1.1
  
  rxdart: ^0.27.7
  shared_preferences: ^2.1.1
  shimmer: ^2.0.0
  syncfusion_flutter_charts: ^21.2.9
  syncfusion_flutter_datagrid: ^21.2.4
  tab_container: ^2.0.0
  transparent_image: ^2.0.1
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.6.2
  build_runner: ^2.4.4
  msix: ^3.12.2
  custom_lint: ^0.4.0
  riverpod_lint: ^1.3.2
  riverpod_generator: ^2.2.3

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
    - assets/json/
    - shorebird.yaml

  fonts:
    - family: TwitterIcon
      fonts:
        - asset: assets/fonts/icons.ttf
    - family: MyanUni
      fonts:
        - asset: assets/fonts/MyanUni/pds_regular.ttf
    - family: YT
      fonts:
        - asset: assets/fonts/yt.ttf
    - family: MS
      fonts:
        - asset: assets/fonts/myan_san.ttf

msix_config:
  display_name: Safe Blood
  #publisher: CN=7CE8207B-1F21-4956-8CDC-1A8029A0BC59
  publisher_display_name: Za Information Technology Co.,Ltd.
  identity_name: ZaInformationTechnologyCo.POSGlobalMarketplace
  msix_version: 1.4.1.0
  logo_path: C:\Users\Administrator\Desktop\ic_launcher.png
  #certificate_path: C:\Users\Administrator\Desktop\MyCert.pfx
  #certificate_password: zatest
