name: merchant
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.1
  animated_widgets: ^1.1.0
  charts_flutter: ^0.12.0
  cloud_firestore: ^3.1.6
  dio: ^4.0.4
  dotted_line: ^3.1.0
  firebase_core: ^1.11.0
  flutter:
    sdk: flutter
  flutter_custom_dialog: ^1.2.0
  flutter_hooks: ^0.18.1
  flutter_localizations:
    sdk: flutter
  flutter_neumorphic: ^3.2.0
  flutter_rounded_date_picker: ^2.0.2
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.0.0
  flutter_typeahead: ^3.2.1
  flutter_zoom_drawer: ^2.1.2
  # google_fonts: ^2.3.2
  hooks_riverpod: ^1.0.3
  http: ^0.13.4
  infinite_scroll_pagination: ^3.1.0
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  objectbox: ^1.4.1
  objectbox_flutter_libs: ^1.4.1
  paginate_firestore: ^1.0.3
  shared_preferences: ^2.0.11
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  json_serializable: ^6.1.3
  build_runner: ^2.1.7
  objectbox_generator: ^1.4.1
  msix: ^2.8.2

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
    - assets/json/

  fonts:
    - family: YT
      fonts:
        - asset: assets/fonts/yt.ttf

msix_config:
  display_name: Safe Blood
  publisher: CN=7CE8207B-1F21-4956-8CDC-1A8029A0BC59
  publisher_display_name: Za Information Technology Co.,Ltd.
  identity_name: ZaInformationTechnologyCo.POSGlobalMarketplace
  msix_version: 1.0.0.0
  logo_path: C:\Users\Administrator\Desktop\Projects\blood_donation\ic_launcher.png
  certificate_path: C:\Users\Administrator\Desktop\MyCert.pfx
  certificate_password: zatest
