name: merchant
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  animated_widgets: ^1.1.0
  # charts_flutter: ^0.12.0
  cloud_firestore: ^4.3.0
  dio: ^4.0.6
  dotted_line: ^3.1.0
  dropdown_button2: ^1.9.2
  firebase_core: ^2.4.0
  fl_chart: ^0.55.2
  fluent_ui: ^4.6.1
  flutter:
    sdk: flutter
  flutter_cupertino_date_picker_fork: ^1.0.7
  flutter_custom_dialog: ^1.3.0
  flutter_expandable_table: ^1.1.1
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  flutter_neumorphic: ^3.2.0
  flutter_rounded_date_picker: ^3.0.2
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.6
  flutter_typeahead: ^4.3.2
  flutter_zoom_drawer: ^3.0.3
  # google_fonts: ^2.3.2
  
  hooks_riverpod: ^2.3.1
  http: ^0.13.5
  infinite_scroll_pagination: ^3.2.0
  logger: ^1.1.0
  modal_progress_hud_nsn: ^0.3.0
  realm: ^1.0.3
  riverpod_annotation: ^2.0.1
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  syncfusion_flutter_datagrid: ^20.4.43
  tab_container: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  json_serializable: ^6.1.3
  build_runner: ^2.3.3
  msix: ^3.7.0
  custom_lint: ^0.3.2
  riverpod_lint: ^1.1.5
  riverpod_generator: ^2.1.3

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
    - assets/json/

  fonts:
    - family: YT
      fonts:
        - asset: assets/fonts/yt.ttf
    - family: MS
      fonts:
        - asset: assets/fonts/myan_san.ttf

msix_config:
  display_name: Safe Blood
  publisher: CN=7CE8207B-1F21-4956-8CDC-1A8029A0BC59
  publisher_display_name: Za Information Technology Co.,Ltd.
  identity_name: ZaInformationTechnologyCo.POSGlobalMarketplace
  msix_version: 1.0.0.0
  logo_path: C:\Users\Administrator\Desktop\Projects\blood_donation\ic_launcher.png
  certificate_path: C:\Users\Administrator\Desktop\MyCert.pfx
  certificate_password: zatest
