// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7l_EuRjHJ_T5njfDgRUeZCXwTesTT-OE',
    appId: '1:1000702292405:web:e1d0a67f2244013a3ca9fc',
    messagingSenderId: '1000702292405',
    projectId: 'redjuniors-be113',
    authDomain: 'redjuniors-be113.firebaseapp.com',
    storageBucket: 'redjuniors-be113.appspot.com',
    measurementId: 'G-SW4NNFXXMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBppdOvOvt0DVFOEvSWbW-6m3yw3Kja74I',
    appId: '1:1000702292405:android:a1b773111a7871f73ca9fc',
    messagingSenderId: '1000702292405',
    projectId: 'redjuniors-be113',
    storageBucket: 'redjuniors-be113.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3tjrpnTQ4mX1YrYwiE5qLB0ft3Dk3E5o',
    appId: '1:1000702292405:ios:1dd587af064761d33ca9fc',
    messagingSenderId: '1000702292405',
    projectId: 'redjuniors-be113',
    storageBucket: 'redjuniors-be113.appspot.com',
    iosClientId:
        '1000702292405-coq349vqnq466g6rni4nao7bee4rjoj0.apps.googleusercontent.com',
    iosBundleId: 'com.red.juniors',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3tjrpnTQ4mX1YrYwiE5qLB0ft3Dk3E5o',
    appId: '1:1000702292405:ios:1dd587af064761d33ca9fc',
    messagingSenderId: '1000702292405',
    projectId: 'redjuniors-be113',
    storageBucket: 'redjuniors-be113.appspot.com',
    iosClientId:
        '1000702292405-coq349vqnq466g6rni4nao7bee4rjoj0.apps.googleusercontent.com',
    iosBundleId: 'com.red.juniors',
  );
}
